In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'i am a good boy',
      'I am good developer',
      'understand the meaning of words',
      'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'I am good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

In [6]:
#One hot representation
onehot_repre=[one_hot(words,voc_size)for words in sent]
print(onehot_repre)

[[946, 1093, 979, 6375], [946, 1093, 979, 6335], [946, 640, 979, 6965], [5445, 4312, 9448, 8493, 5039], [5445, 4312, 8493, 1372], [375, 946, 5555, 979, 2983], [9951, 9674, 6354, 8493]]


In [10]:
#word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(onehot_repre,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  946 1093  979 6375]
 [   0    0    0    0  946 1093  979 6335]
 [   0    0    0    0  946  640  979 6965]
 [   0    0    0 5445 4312 9448 8493 5039]
 [   0    0    0    0 5445 4312 8493 1372]
 [   0    0    0  375  946 5555  979 2983]
 [   0    0    0    0 9951 9674 6354 8493]]


In [13]:
dim=15

In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[-3.26701775e-02 -4.91055138e-02 -2.29530465e-02 -1.76975727e-02
   -4.70877290e-02 -3.40080261e-02 -9.58539173e-03  4.00408395e-02
    8.84901360e-03 -3.45107093e-02]
  [-3.26701775e-02 -4.91055138e-02 -2.29530465e-02 -1.76975727e-02
   -4.70877290e-02 -3.40080261e-02 -9.58539173e-03  4.00408395e-02
    8.84901360e-03 -3.45107093e-02]
  [-3.26701775e-02 -4.91055138e-02 -2.29530465e-02 -1.76975727e-02
   -4.70877290e-02 -3.40080261e-02 -9.58539173e-03  4.00408395e-02
    8.84901360e-03 -3.45107093e-02]
  [-3.26701775e-02 -4.91055138e-02 -2.29530465e-02 -1.76975727e-02
   -4.70877290e-02 -3.40080261e-02 -9.58539173e-03  4.00408395e-02
    8.84901360e-03 -3.45107093e-02]
  [ 3.74412201e-02  8.90221447e-03 -1.80098303e-02 -1.40188821e-02
    3.09264176e-02  3.39397229e-02  4.50161807e-02  4.54099067e-02
   -6.59907982e-03  1.05871074e-02]
  [-3.16690654e-04 -8.26741382e-03  1.57766230e-02 -4.03178111e-02
   -4.73249070e-02 -3.81637737e-03 -3.27422768e-02  3.61427665e-05
   -1.15279183e-

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0,  946, 1093,  979, 6375], dtype=int32)